### ISSUE TITLE
Scrolling gesture only works on the edge 

### ISSUE THREAD

**Issue by JoeCotellese** [jaesung-0o0/ChatUI#26]
I'm noticing that on chat interactions with a long chat post you can't scroll by swiping over chat bubbles. See screenshot from my app. 

I've also reproduced this in the Quickstart example.

![IMG_F50039FA06F4-1](https://user-images.githubusercontent.com/1251258/227531345-3932f5ec-f021-4a9d-82f7-819c674e766b.jpeg)

IMO the expected behavior is that the entire chat canvas is supports the scrolling gesture.

**Comment by jaesung-0o0** [comment]
@JoeCotellese 
✨Thanks for letting me know the issue! 
🎯I'm going to resolve this issue from the upcoming version: `1.0.0-beta.8`.
🔔After the release, I'll remind you!

**Comment by JoeCotellese** [comment]
Any updates on this beta 8?

**Comment by jaesung-0o0** [comment]
> Any updates on this beta 8?

Sorry for the delay on the deployment.

https://github.com/jaesung-0o0/ChatUI/discussions/27

As I announced here, I pause my work until the end of April because of personal issue!

If you use it by forking, you might resolve the issue by 2 ways:
- set up frame size of scroll view to fit in the screen.
- modify tap gesture or long tap gesture on Message list body

**Comment by jaesung-0o0** [comment]
Hi, @JoeCotellese 
✨ Thank you for waiting patiently. 
🚀 The bug you reported has been fixed and the 8th beta version (1.0.0-beta.8) has been released.
